### ISSUE TITLE
Getting error when deploying

### ISSUE THREAD

**Issue by jackandjill** [ponnex/BidHub-CloudCode#1]
Hi, 
I am getting error when deploying opened a question here, kindly assist really appreciate your help.

http://stackoverflow.com/questions/35014307/parse-deploy-code-not-working?noredirect=1#comment57758434_35014307

**Comment by ponnex** [comment]
Create a new Parse app and copy the JS script or use existing. Please refer to https://parse.com/docs/cloudcode/guide#command-line

**Comment by jackandjill** [comment]
U tried with windows or mac?

**Comment by ponnex** [comment]
windows

**Comment by jackandjill** [comment]
ah! ok u saw my screenshot is for mac.. ok i try on windows now

**Comment by jackandjill** [comment]
Yup it works. i think I know where I made mistake even in my MAC, but the error is not as clear as Windows. Thanks. One more question there is supposed to be only cloudcode and nothing else?

**Comment by ponnex** [comment]
This cloud code is for an app "BidHub-Android" it takes care of all the "automatic" push notifications and other background work for the app. You can refer to HubSpot or my fork repo of their app ;) happy coding!

NOTE: this is one commit ahead as I made some fixes which I have encountered before using the one from HubSpot, so If you plan on playing or exploring more into this, I suggest you use this repo

**Comment by jackandjill** [comment]
Will do! Thanks for your efforts buddy!
